version: '2.1'
orbs:
  node: circleci/node@4.7
jobs:
  deploy_docs:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/node_modules
          override-ci-command: npm install
      - run: npm run deploy
workflows:
  deploy_docs:
    jobs:
      - deploy_docs
