version: '2.1'
orbs:
  node: circleci/node@4.7
jobs:
  deploy_docs:
    executor: node/default
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "17:69:37:79:cb:8e:d1:35:d4:35:27:13:d9:67:56:d0"
      - node/install-packages:
          cache-path: ~/node_modules
          override-ci-command: npm install
      - run: 
          name: "set git username"
          command: |
              git config user.email "kirubakarthikeyan07@gmail.com"
              git config user.name "Kiruba Karan"
      - run: 
          name: "Initializing deployment"
          command: npm run deploy


workflows:
  deploy_docs:
    jobs:
      - deploy_docs
