version: '2.1'
orbs:
  node: circleci/node@4.7
jobs:
  deploy_docs:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/node_modules
          override-ci-command: npm install
      - run: 
          name: "set git username"
          command: |
              git config user.email "kirubakarthikeyan07@gmail.com"
              git config user.name "Kiruba Karan"
      - run: 
          name: "Initializing deployment"
          command: npm run deploy


workflows:
  deploy_docs:
    jobs:
      - deploy_docs
